#!/bin/sh

[ -z "${TOKEN}" ] && {
  echo "curlit: set your session token with 'export TOKEN=...'" >&2
  exit 1
}

METHOD=${1:-GET}
shift

P=${1:-"/"}
shift

ARG=${ARG:-"-s"}

curl \
  ${ARG} \
  -u "x:${TOKEN}" \
  -X ${METHOD} \
  -H 'Content-type: application/json' \
  -H 'Accept: application/json' \
  http://localhost:3000${P} "$@"

echo
